### ISSUE TITLE
Feature: Allow Individual Draws

### ISSUE THREAD

**Issue by bjjones** [JiangYizhou/aquarium-test#9]
In order to further stress the Dawn backend, we should increase the number of Draw() calls. Currently `DrawIndexed()` is used to draw many instances at once. Using `DrawIndexed()` in this case is optimal - however, by instead calling `Draw()` many times, we can better emulate a modern graphics application.

I suggest that in models that have high instance counts (particularly `FishModel`), a separate path that uses `Draw()` instead of `DrawIndexed()` should be available. A command line parameter can be added that will switch the path on. Perhaps `--allowIndividualDraws`?

**Comment by JiangYizhou** [comment]
This requires dynamic buffer offset feature in Dawn. Shaobo is implementing the feature https://github.com/gpuweb/gpuweb/issues/116.

**Comment by bjjones** [comment]
Has there been any consideration to doing an individual draw implementation without dynamic buffer offsets?

Instead we could create a fishPer buffer for every fish, bind it and call draw for every individual fish.

**Comment by JiangYizhou** [comment]
This commit add individual draw to Aquarium dawn backend. The patch works well on dawn vulkan backend but crashes on d3d12 backend if rendering more than 10000 fishes.  @bjjones @Jiawei-Shao @Kangz 
It seems to failed to CreateConstantBufferView in d3d12 backend.
>	aquarium.exe!dawn_native::d3d12::BindGroup::RecordDescriptors

**Comment by bjjones** [comment]
I've taken a quick look, and with individual draws we are CPU bound. I think this is what a lot of people were looking for. Thanks again for all the work Yizhou!

I'll begin working on the D3D12 failure.

**Comment by Jiawei-Shao** [comment]
Hi @bjjones , this is because currently the size of cbvSrvUavCPUDescriptorHeap used in Dawn is always 8192 (https://cs.chromium.org/chromium/src/third_party/dawn/src/dawn_native/d3d12/CommandBufferD3D12.cpp?l=278), so when we want to create more than 8192 views from this heap, Dawn will crash at https://cs.chromium.org/chromium/src/third_party/dawn/src/dawn_native/d3d12/BindGroupD3D12.cpp?l=60.

@Kangz I think there could be a simple fix in Dawn that we just create the cbvSrvUavCPUDescriptorHeap after counting how many views we actually need in the current command buffer, just like what we do now for RTV and DSV heaps.(https://cs.chromium.org/chromium/src/third_party/dawn/src/dawn_native/d3d12/CommandBufferD3D12.cpp?l=204)

**Comment by JiangYizhou** [comment]
@shaoboyan @gyagp @Richard-Yunchao

**Comment by JiangYizhou** [comment]
The descriptor heap issue on dawn d3d12 has been fixed by Jiawei. And the performance of drawing fishes individually is quite good comparing to dawn vulkan.

**Comment by JiangYizhou** [comment]
This issue is fixed.
